[build]
  command = "cd ../.. && bun install --no-save && cd apps/songmaking && bun run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=/dev/null"
